export const CarouselData = [
    {
        cards: [
            {
                id: 1,
                title: "Bottega",
                desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
                stars: ["full", "full", "full", "full", "full"],
                reviews: 876,
                rating: "5.0",
                images: ["card-image-1.png", "card-image-2.png", "card-image-3.png", "card-image-4.png"],
            },
            {
                id: 2,
                title: "Hello",
                desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
                stars: ["full", "full", "full", "full", "full"],
                reviews: 876,
                rating: "5.0",
                images: ["card-image-2.png", "card-image-1.png", "card-image-3.png", "card-image-4.png"],
            },
            {
                id: 3,
                title: "Fishes",
                desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
                stars: ["full", "full", "full", "full", "full"],
                reviews: 876,
                rating: "5.0",
                images: ["card-image-3.png", "card-image-1.png", "card-image-2.png", "card-image-4.png"],
            },
            {
                id: 4,
                title: "Shopping",
                desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
                stars: ["full", "full", "full", "full", "full"],
                reviews: 876,
                rating: "5.0",
                images: ["card-image-4.png", "card-image-1.png", "card-image-3.png", "card-image-2.png"],
            },
        ]
    },
    {
        cards: [
            {
                id: 1,
                title: "Fishes",
                desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
                stars: ["full", "full", "full", "full", "full"],
                reviews: 876,
                rating: "5.0",
                images: ["card-image-3.png", "card-image-1.png", "card-image-2.png", "card-image-4.png"],
            },
            {
                id: 2,
                title: "Shopping",
                desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
                stars: ["full", "full", "full", "full", "full"],
                reviews: 876,
                rating: "5.0",
                images: ["card-image-4.png", "card-image-1.png", "card-image-3.png", "card-image-2.png"],
            },
            {
                id: 3,
                title: "Hello",
                desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
                stars: ["full", "full", "full", "full", "full"],
                reviews: 876,
                rating: "5.0",
                images: ["card-image-2.png", "card-image-1.png", "card-image-3.png", "card-image-4.png"],
            },
            {
                id: 4,
                title: "Bottega",
                desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
                stars: ["full", "full", "full", "full", "full"],
                reviews: 876,
                rating: "5.0",
                images: ["card-image-1.png", "card-image-3.png", "card-image-3.png", "card-image-4.png"],
            },
        ]
    },
]
export const latestCardData = [
    {
        id: 1,
        title: "Bella Italia",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "empty"],
        reviews: 34,
        rating: "4.8",
        images: ["card-image-5.png", "card-image-8.png", "card-image-7.png", "card-image-6.png"],
    },
    {
        id: 2,
        title: "Little Shucker",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "full"],
        reviews: 253,
        rating: "5.0",
        images: ["card-image-6.png", "card-image-10.png", "card-image-7.png", "card-image-6.png"],
    },
    {
        id: 3,
        title: "Marafuku Ramen",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "empty", "empty"],
        reviews: 876,
        rating: "3.5",
        images: ["card-image-7.png", "card-image-10.png", "card-image-8.png", "card-image-6.png"],
    },
    {
        id: 4,
        title: "Bottega",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "full"],
        reviews: 876,
        rating: "5.0",
        images: ["card-image-8.png", "card-image-10.png", "card-image-7.png", "card-image-8.png"],
    },
    {
        id: 5,
        title: "Bottega",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "half", "empty"],
        reviews: 334,
        rating: "3.5",
        images: ["card-image-9.png", "card-image-8.png", "card-image-7.png", "card-image-6.png"],
    },
    {
        id: 6,
        title: "Hello",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "full"],
        reviews: 876,
        rating: "5.0",
        images: ["card-image-10.png", "card-image-10.png", "card-image-7.png", "card-image-6.png"],
    },
    {
        id: 7,
        title: "Fishes",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "full"],
        reviews: 876,
        rating: "4.5",
        images: ["card-image-11.png", "card-image-10.png", "card-image-8.png", "card-image-6.png"],
    },
    {
        id: 8,
        title: "Shopping",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "full"],
        reviews: 876,
        rating: "5.0",
        images: ["card-image-12.png", "card-image-10.png", "card-image-7.png", "card-image-8.png"],
    },
    {
        id: 9,
        title: "Iori",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "half", "empty"],
        reviews: 234,
        rating: "3.4",
        images: ["card-image-13.png", "card-image-8.png", "card-image-7.png", "card-image-6.png"],
    },
    {
        id: 10,
        title: "Ngalley",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "half"],
        reviews: 876,
        rating: "4.5",
        images: ["card-image-14.png", "card-image-10.png", "card-image-7.png", "card-image-6.png"],
    },
    {
        id: 11,
        title: "diogonal",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "full"],
        reviews: 876,
        rating: "5.0",
        images: ["card-image-15.png", "card-image-10.png", "card-image-8.png", "card-image-6.png"],
    },
    {
        id: 12,
        title: "Kitoko",
        desc: "The lorem ipsum is, in printing, a series of meaningless words used temporarily to calibrate a layout.",
        stars: ["full", "full", "full", "full", "full"],
        reviews: 876,
        rating: "5.0",
        images: ["card-image-16.png", "card-image-10.png", "card-image-7.png", "card-image-8.png"],
    },
]